
'use strict';
const $=id=>document.getElementById(id), LOCAL_KEY='18ji-no-mikata-v2', OLD='18ji-no-mikata';
let KEY=LOCAL_KEY;
try{const active=localStorage.getItem('happy-active-scope');if(active&&active.startsWith('happy-user:'))KEY=active}catch{}
const pad=n=>String(n).padStart(2,'0');
function dateKey(d=new Date()){return d.getFullYear()+'-'+pad(d.getMonth()+1)+'-'+pad(d.getDate())}
function parseDate(k){return new Date(k+'T12:00:00')}
function minute(t){const a=t.split(':').map(Number);return a[0]*60+a[1]}
function hhmm(m){m=((Math.round(m)%1440)+1440)%1440;return pad(Math.floor(m/60))+':'+pad(m%60)}
function duration(sec){sec=Math.max(0,Math.ceil(sec));return pad(Math.floor(sec/60))+':'+pad(sec%60)}
function countdown(sec){sec=Math.max(0,Math.ceil(sec));return pad(Math.floor(sec/3600))+':'+pad(Math.floor(sec/60)%60)+':'+pad(sec%60)}
const routineDefaults=[{id:'wake',name:'起きて、水を飲む',min:3},{id:'wash',name:'洗顔・歯みがき',min:8},{id:'breakfast',name:'朝ごはん',min:15},{id:'dress',name:'着替え・身支度',min:14},{id:'bag',name:'鍵・財布・持ち物を確認',min:5}];
const defaults={start:'07:50',end:'18:00',commute:40,arrival:5,breaks:60,sleep:8,place:'',weekdays:[1,2,3,4,5],routine:routineDefaults,reward:'好きなごはん ＋ ゆっくり過ごす'};
let storageOK=true, state;
try{state=JSON.parse(localStorage.getItem(KEY)||'null')}catch{storageOK=false}
if(!state || state.version!==2 || !state.settings || !state.days){
 let legacy={};try{if(KEY===LOCAL_KEY)legacy=JSON.parse(localStorage.getItem(OLD)||'{}')||{}}catch{}
 state={version:2,settings:{...defaults},days:{},timer:null};
 for(const k of ['start','end','reward'])if(typeof legacy[k]==='string' && legacy[k])state.settings[k]=legacy[k];
 if(Number.isFinite(legacy.commute))state.settings.commute=legacy.commute;
 // The old buffer described total preparation time; keep that preference proportionally.
 if(Number.isFinite(legacy.buffer)&&legacy.buffer>0){state.settings.routine=routineDefaults.map((r,i)=>({...r,min:i===4?Math.max(1,legacy.buffer-4*Math.max(1,Math.floor(legacy.buffer/5))):Math.max(1,Math.floor(legacy.buffer/5))}))}
}
state.settings={...defaults,...state.settings};
let today=dateKey(), toastHandle, heroTarget='morning', incomingNote=null, applyingCloud=false;
function nextWorkDate(key){let d=parseDate(key);for(let i=0;i<7;i++){d.setDate(d.getDate()+1);if(state.settings.weekdays.includes(d.getDay()))return dateKey(d)}return dateKey(d)}
function day(){if(!state.days[today])state.days[today]={morning:{},tasks:Array.from({length:3},()=>({text:'',done:false})),reward:state.settings.reward,enjoyed:false,note:{next:'',loose:'',win:'',target:nextWorkDate(today)},night:{},finished:false,focus:0};return state.days[today]}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));storageOK=true}catch{storageOK=false}$('storageWarning').hidden=storageOK;$('saveStatus').textContent=storageOK?'このブラウザに自動保存':'保存できません';if(!applyingCloud)window.dispatchEvent(new CustomEvent('happy:change'));}
function toast(text){$('toast').textContent=text;$('toast').classList.add('show');clearTimeout(toastHandle);toastHandle=setTimeout(()=>$('toast').classList.remove('show'),3200)}
function celebrate(button){if(!window.matchMedia('(prefers-reduced-motion: reduce)').matches){const r=button.getBoundingClientRect();for(let i=0;i<4;i++){const el=document.createElement('span');el.className='spark';el.textContent=['✿','✦','❋','✧'][i];el.style.left=(r.left+r.width/2+(i-1.5)*24)+'px';el.style.top=(r.top+window.scrollY-window.scrollY)+'px';el.style.color=['#63834e','#c6844e','#b46d75','#6d896c'][i];document.body.append(el);setTimeout(()=>el.remove(),1400)}}}
function schedule(){const s=state.settings,start=minute(s.start),end=minute(s.end),prep=s.routine.reduce((a,r)=>a+r.min,0),leave=start-s.commute-s.arrival,wake=leave-prep;return{start,end,prep,leave,wake,bed:wake-s.sleep*60}}
function dateLabel(key){return parseDate(key).toLocaleDateString('ja-JP',{month:'numeric',day:'numeric',weekday:'short'})}
function score(d){return Object.values(d.morning).filter(Boolean).length+d.tasks.filter(t=>t.done&&t.text.trim()).length+(d.focus||0)+(d.finished?1:0)+(d.enjoyed?1:0)}
function renderGarden(){const box=$('flowers');box.replaceChildren();let sum=0;for(let i=6;i>=0;i--){const d=parseDate(today);d.setDate(d.getDate()-i);const k=dateKey(d),entry=state.days[k],points=entry?score(entry):0;sum+=points;const el=document.createElement('div');el.className='flower-day';el.title=dateLabel(k)+'：'+points+'個のできた';const flower=document.createElement('span');flower.textContent=points>=7?'🌻':points>=3?'🌼':points>0?'🌱':'·';const label=document.createElement('small');label.textContent=i===0?'今日':(d.getMonth()+1)+'/'+d.getDate();el.append(flower,label);box.append(el)}$('gardenSummary').replaceChildren(document.createTextNode(sum+' '));const sm=document.createElement('small');sm.textContent='個のできたが、この庭に。';$('gardenSummary').append(sm)}
function renderMorning(){const d=day(),s=state.settings,p=schedule();let time=p.wake;const list=$('routineList');list.replaceChildren();s.routine.forEach(r=>{const label=document.createElement('label');label.className='routine-row'+(d.morning[r.id]?' done':'');const input=document.createElement('input');input.type='checkbox';input.checked=!!d.morning[r.id];input.addEventListener('change',()=>{day().morning[r.id]=input.checked;save();renderMorning();renderGarden();if(input.checked)toast('ひとつ進んだ。いい調子。')});const text=document.createElement('span');text.className='text';const name=document.createElement('span');name.textContent=r.name;const small=document.createElement('small');small.textContent=r.min+'分の目安';text.append(name,small);const t=document.createElement('span');t.className='time-tag';t.textContent=hhmm(time);time+=r.min;label.append(input,text,t);list.append(label)});
 const done=s.routine.filter(r=>d.morning[r.id]).length, next=s.routine.find(r=>!d.morning[r.id]);$('morningCount').textContent=done+' / '+s.routine.length;$('morningBar').style.width=(done/s.routine.length*100)+'%';$('morningProgress').setAttribute('aria-valuenow',Math.round(done/s.routine.length*100));$('nextStep').textContent=next?next.name:'準備できた。いってらっしゃい！';$('nextHint').textContent=next?next.min+'分を目安に。出発は '+hhmm(p.leave)+'。':'忘れ物を確認して、自分のペースで出発。';$('nextDone').disabled=!next}
function renderTasks(){const box=$('tasks');box.replaceChildren();day().tasks.forEach((t,i)=>{const row=document.createElement('div');row.className='task-row';const check=document.createElement('input');check.type='checkbox';check.checked=t.done;check.setAttribute('aria-label','タスク'+(i+1)+'を完了');const input=document.createElement('input');input.type='text';input.value=t.text;input.maxLength=180;input.placeholder=['まずはこれだけ','次に進めたいこと','余裕があれば'][i];input.setAttribute('aria-label','タスク'+(i+1));check.addEventListener('change',()=>{if(check.checked&&!input.value.trim()){check.checked=false;input.focus();return}day().tasks[i].done=check.checked;save();renderCounts();renderGarden();if(check.checked){toast('できたをひとつ、庭に。');celebrate(check)}});input.addEventListener('input',()=>{day().tasks[i].text=input.value;if(!input.value.trim()){day().tasks[i].done=false;check.checked=false}save();renderCounts();renderGarden()});row.append(check,input);box.append(row)});renderCounts()}
function renderCounts(){$('taskCount').textContent=day().tasks.filter(t=>t.done&&t.text.trim()).length+' / 3';$('focusSummary').textContent='今日の集中 '+day().focus+'回。タイマーは再読み込みしても続きます。'}
function renderIncoming(){const candidates=Object.keys(state.days).filter(k=>k<today&&state.days[k].note&&(state.days[k].note.next||state.days[k].note.loose)&&state.days[k].note.target<=today).sort();const k=candidates.at(-1);incomingNote=k?state.days[k].note:null;$('incoming').hidden=!incomingNote;if(incomingNote){$('incomingDate').textContent=dateLabel(k)+'の自分から届いたメモ';$('incomingText').textContent=[incomingNote.next,incomingNote.loose].filter(Boolean).join('\n\n');$('useIncoming').hidden=!incomingNote.next}}
function renderRoute(){const p=schedule();const entries=[['起きる',p.wake],['家を出る',p.leave],['仕事を始める',p.start],['仕事を終える',p.end],['帰宅の目安',p.end+state.settings.commute]];const route=$('route');route.replaceChildren();entries.forEach(([label,time])=>{const div=document.createElement('div');div.className='stop';div.dataset.time=time;const b=document.createElement('b');b.textContent=hhmm(time);const sm=document.createElement('small');sm.textContent=label;div.append(b,sm);route.append(div)});$('scheduleCaption').textContent=state.settings.weekdays.includes(new Date().getDay())?'今日の予定':'今日は休日設定';const net=p.end-p.start-state.settings.breaks;$('routeNote').textContent='通勤 '+state.settings.commute+'分 ＋ 到着後 '+state.settings.arrival+'分の余裕 ／ 朝の準備 '+p.prep+'分 ／ 休憩を除く予定 '+Math.floor(net/60)+'時間'+(net%60?net%60+'分':'')+(state.settings.place?' ／ 始める場所：'+state.settings.place:'');const next=nextWorkDate(today);$('bedtime').textContent='次の仕事日の起床は '+hhmm(p.wake);$('bedtimeHint').textContent=dateLabel(next)+'の朝に向けて、前日の '+hhmm(p.bed)+' ごろを就寝目安に。睡眠 '+state.settings.sleep+'時間で計算しています。'}
function renderDay(){const d=day();$('today').textContent=new Date().toLocaleDateString('ja-JP',{month:'long',day:'numeric',weekday:'short'});$('reward').value=d.reward;$('rewardTitle').textContent=d.reward||'今日の楽しみを決めよう';$('enjoyReward').textContent=d.enjoyed?'楽しんだ ✓（戻す）':'楽しんだ ✓';$('nextAction').value=d.note.next;$('looseEnds').value=d.note.loose;$('smallWin').value=d.note.win;$('noteTarget').textContent=dateLabel(d.note.target)+'へ';$('nightBag').checked=!!d.night.bag;$('nightClothes').checked=!!d.night.clothes;$('finishDay').textContent=d.finished?'退勤を記録済み ✓（戻す）':'今日はここまで。帰ろう ↗';renderMorning();renderTasks();renderIncoming();renderRoute();renderGarden();tick()}
function tick(){const now=new Date();if(dateKey(now)!==today){today=dateKey(now);renderDay();save();return}
 const p=schedule(),m=now.getHours()*60+now.getMinutes()+now.getSeconds()/60,d=day();let title,target,phase,hint,action;
 if(d.finished){phase='自分の時間';title='今日も、おつかれさま。';target=null;hint='明日のメモは預かりました。今日のご褒美を楽しもう。';action='明日の準備を見る';heroTarget='tomorrow'}
 else if(!state.settings.weekdays.includes(now.getDay())){phase='お休みの日';title='今日は、自分の時間。';target=null;hint='次の仕事日は '+dateLabel(nextWorkDate(today))+'。予定は自分に合わせて。';action='次の朝を準備する';heroTarget='tomorrow'}
 else if(m<p.wake){phase='朝を迎える前';title='起きる目安まで';target=p.wake;hint='起床 '+hhmm(p.wake)+' → 出発 '+hhmm(p.leave)+'。今は休む時間も大切に。';action='朝の準備を見ておく';heroTarget='morning'}
 else if(m<p.leave){phase='朝の準備';title='家を出るまで、あと';target=p.leave;hint='次のひとつをチェック。'+hhmm(p.start)+'に仕事を始める予定です。';action='朝の一歩を進める';heroTarget='morning'}
 else if(m<p.start){phase='移動・到着';title='始業の目安まで';target=p.start;hint='出発目安は '+hhmm(p.leave)+'。まだ家なら、安全に移動できる予定に調整しよう。';action='今日の最初の一手へ';heroTarget='work'}
 else if(m<p.end-15){phase='仕事の時間';title='仕事を終えるまで、あと';target=p.end;hint='ご褒美も、今日の予定。'+hhmm(p.end-15)+'から片づけを始めよう。';action='ひとつだけ、集中する';heroTarget='work'}
 else if(m<p.end){phase='帰る準備';title='今日を閉じるまで、あと';target=p.end;hint='途中のことをメモに預けて、帰る準備を。';action='明日の自分へメモ';heroTarget='tomorrow'}
 else{phase='退勤の時間';title='ご褒美の時間です。';target=null;hint='今日の続きは、明日の自分へ。ひと区切りつけよう。';action='メモして、今日はここまで';heroTarget='tomorrow'}
 $('phase').textContent=phase;$('countTitle').textContent=title;$('countdown').textContent=target===null?'おつかれさま':countdown((target-m)*60);$('countdown').style.fontSize=target===null?'clamp(28px,3.4vw,46px)':'';$('heroHint').textContent=hint;$('heroAction').textContent=action;document.querySelectorAll('.stop').forEach(el=>el.classList.toggle('passed',m>=Number(el.dataset.time)));tickTimer()}
function timer(){if(!state.timer)state.timer={minutes:25,remaining:1500,endAt:null,day:today};return state.timer}
function tickTimer(){const t=timer();if(t.endAt&&Date.now()>=t.endAt){if(t.minutes!==5){if(state.days[t.day])state.days[t.day].focus++}t.endAt=null;t.remaining=0;save();renderCounts();renderGarden();toast(t.minutes===5?'休憩、おつかれさま。次も自分のペースで。':'ひと区切りできた！少し休憩しよう。')}
 const left=t.endAt?(t.endAt-Date.now())/1000:t.remaining;$('timerClock').textContent=duration(left);$('timerLabel').textContent=t.minutes===5?'TAKE A BREAK':'FOCUS TIME';$('timerToggle').textContent=t.endAt?'一時停止':left===0?'もう一度はじめる':left<t.minutes*60?'続きから':t.minutes===5?'休憩する':'集中をはじめる';document.querySelectorAll('[data-min]').forEach(el=>{el.setAttribute('aria-pressed',Number(el.dataset.min)===t.minutes);el.disabled=!!t.endAt})}
$('timerToggle').onclick=()=>{const t=timer();if(t.endAt){t.remaining=Math.max(0,(t.endAt-Date.now())/1000);t.endAt=null}else{if(t.remaining<=0)t.remaining=t.minutes*60;t.endAt=Date.now()+t.remaining*1000;t.day=today}save();tickTimer()};
$('timerReset').onclick=()=>{const t=timer();t.endAt=null;t.remaining=t.minutes*60;save();tickTimer()};
document.querySelectorAll('[data-min]').forEach(b=>b.onclick=()=>{state.timer={minutes:Number(b.dataset.min),remaining:Number(b.dataset.min)*60,endAt:null,day:today};save();tickTimer()});
$('heroAction').onclick=()=>$(heroTarget).scrollIntoView({block:'start'});
$('nextDone').onclick=()=>{const r=state.settings.routine.find(r=>!day().morning[r.id]);if(!r)return;day().morning[r.id]=true;save();celebrate($('nextDone'));renderMorning();renderGarden();toast('ひとつ進んだ。次もゆっくり。')};
$('reward').addEventListener('input',()=>{day().reward=$('reward').value;state.settings.reward=day().reward;$('rewardTitle').textContent=day().reward||'今日の楽しみを決めよう';save()});
let rewardIndex=0;const ideas=['好きなごはん ＋ ゲーム30分','お風呂でゆっくり、そのあとアイス','気になっていた本を1章だけ','お気に入りの音楽で、帰り道を楽しむ','何もしない時間を、堂々と過ごす'];
$('suggestReward').onclick=()=>{day().reward=ideas[rewardIndex++%ideas.length];state.settings.reward=day().reward;$('reward').value=day().reward;$('rewardTitle').textContent=day().reward;save()};
$('enjoyReward').onclick=()=>{day().enjoyed=!day().enjoyed;$('enjoyReward').textContent=day().enjoyed?'楽しんだ ✓（戻す）':'楽しんだ ✓';if(day().enjoyed){celebrate($('enjoyReward'));toast('今日の楽しみ、回収できた。')}save();renderGarden()};
for(const [id,k] of [['nextAction','next'],['looseEnds','loose'],['smallWin','win']])$(id).addEventListener('input',()=>{day().note[k]=$(id).value;save();$('noteStatus').textContent=storageOK?'保存しました。'+dateLabel(day().note.target)+'以降、仕事欄に表示します。':'保存できません。記録を書き出してください。'});
for(const [id,k] of [['nightBag','bag'],['nightClothes','clothes']])$(id).onchange=()=>{day().night[k]=$(id).checked;save()};
$('carryTasks').onclick=()=>{const list=day().tasks.filter(t=>!t.done&&t.text.trim()).map(t=>'・'+t.text.trim());const current=day().note.loose.split('\n');const fresh=list.filter(t=>!current.includes(t));if(!fresh.length){toast('追加する未完了タスクはありません。');return}day().note.loose=[day().note.loose,...fresh].filter(Boolean).join('\n');$('looseEnds').value=day().note.loose;save();toast('続きをメモに預けました。')};
$('finishDay').onclick=()=>{day().finished=!day().finished;save();$('finishDay').textContent=day().finished?'退勤を記録済み ✓（戻す）':'今日はここまで。帰ろう ↗';renderGarden();tick();if(day().finished){celebrate($('finishDay'));toast('今日もおつかれさま。自分の時間へ。')}};
$('useIncoming').onclick=()=>{if(!incomingNote)return;if(day().tasks.some(t=>t.text===incomingNote.next)){toast('もう今日のタスクに入っています。');return}const empty=day().tasks.find(t=>!t.text.trim());if(!empty){toast('3つ埋まっています。入れ替えるタスクを編集してください。');return}empty.text=incomingNote.next;empty.done=false;save();renderTasks();toast('最初の一手を、今日のタスクへ。')};
function renderSettings(){const s=state.settings;for(const k of ['start','end','commute','arrival','breaks','sleep','place'])$(k).value=s[k];const weekdays=$('weekdays');weekdays.replaceChildren();['日','月','火','水','木','金','土'].forEach((name,i)=>{const l=document.createElement('label'),check=document.createElement('input');check.type='checkbox';check.value=i;check.checked=s.weekdays.includes(i);l.append(check,document.createTextNode(name));weekdays.append(l)});$('routineEditor').replaceChildren();s.routine.forEach(addRoutineRow)}
function addRoutineRow(r={id:'r'+Date.now()+Math.random().toString(36).slice(2,5),name:'',min:5}){const row=document.createElement('div');row.className='routine-edit-row';row.dataset.id=r.id;const name=document.createElement('input');name.value=r.name;name.required=true;name.maxLength=80;name.placeholder='準備の名前';name.setAttribute('aria-label','準備の名前');const min=document.createElement('input');min.type='number';min.min=1;min.max=180;min.required=true;min.value=r.min;min.setAttribute('aria-label','準備の時間（分）');const del=document.createElement('button');del.type='button';del.className='ghost';del.textContent='×';del.setAttribute('aria-label','この準備を削除');del.onclick=()=>row.remove();row.append(name,min,del);$('routineEditor').append(row)}
$('addRoutine').onclick=()=>{if($('routineEditor').children.length>=12){toast('朝の準備は12個までにしましょう。');return}addRoutineRow()};
$('settingsForm').onsubmit=e=>{e.preventDefault();const s={...state.settings};for(const k of ['start','end','place'])s[k]=$(k).value;for(const k of ['commute','arrival','breaks','sleep'])s[k]=Number($(k).value);s.weekdays=Array.from($('weekdays').querySelectorAll('input:checked')).map(x=>Number(x.value));s.routine=Array.from($('routineEditor').children).map(row=>({id:row.dataset.id,name:row.children[0].value.trim(),min:Number(row.children[1].value)}));let error='';const span=minute(s.end)-minute(s.start);if(span<=0)error='退勤は始業より後の時刻にしてください。';else if(s.breaks>=span)error='休憩の合計は、始業から退勤までの時間より短くしてください。';else if(!s.weekdays.length)error='仕事の日を1日以上選んでください。';else if(!s.routine.length||s.routine.some(r=>!r.name))error='朝の準備を1つ以上入力してください。';else if(minute(s.start)-s.commute-s.arrival-s.routine.reduce((a,r)=>a+r.min,0)<0)error='起床が前日になっています。朝の支度・始業時刻を調整してください。';$('settingsError').textContent=error;if(error)return;state.settings=s;day().note.target=nextWorkDate(today);save();renderDay();toast('あなたの時間で保存しました。')};
function showHistory(){const body=$('historyBody');body.replaceChildren();const keys=Object.keys(state.days).sort().reverse().filter(k=>{const n=state.days[k].note;return n&&(n.next||n.loose||n.win)});if(!keys.length)body.textContent='メモを書くと、ここに残ります。';for(const key of keys){const n=state.days[key].note;const el=document.createElement('article');el.className='history-entry';const h=document.createElement('h3');h.textContent=dateLabel(key)+' → '+dateLabel(n.target);const p=document.createElement('p');p.textContent=[n.next&&'最初の一手：'+n.next,n.loose&&'続き：'+n.loose,n.win&&'できたこと：'+n.win].filter(Boolean).join('\n\n');el.append(h,p);body.append(el)}$('history').showModal()}
$('historyOpen').onclick=showHistory;$('historyClose').onclick=()=>$('history').close();
function exportData(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='18時の味方-'+today+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('記録を書き出しました。')}
$('exportSide').onclick=exportData;$('exportMain').onclick=exportData;
document.addEventListener('visibilitychange',()=>{if(!document.hidden)tick()});

function freshState(){return{version:2,settings:JSON.parse(JSON.stringify(defaults)),days:{},timer:null}}
window.Happy={
 snapshot:()=>JSON.parse(JSON.stringify({version:2,settings:state.settings,days:state.days})),
 localSnapshot:()=>{try{const saved=JSON.parse(localStorage.getItem(LOCAL_KEY)||'null');return saved?{version:2,settings:saved.settings,days:saved.days}:null}catch{return null}},
 scope:()=>KEY,
 switchScope:(key)=>{if(KEY===key)return;applyingCloud=true;try{save();KEY=key;let saved;try{saved=JSON.parse(localStorage.getItem(key)||'null')}catch{}state=saved&&saved.version===2?saved:freshState();localStorage.setItem('happy-active-scope',key);renderSettings();renderDay();save()}finally{applyingCloud=false}},
 apply:(snapshot)=>{applyingCloud=true;try{state={...snapshot,timer:state.timer};renderSettings();renderDay();save()}finally{applyingCloud=false}},
 toast,
 editing:()=>['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName)
};

renderSettings();renderDay();save();setInterval(tick,1000);

